# Site settings
title: Prasanth Portfolio
description: A portfolio about Prasanth
# baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://github.com/pvsp2003/pvsprasanth.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: PVS Prasanth
user_description: I am a passionate software developer with experience in full-stack development, data analytics, and AI. I enjoy building efficient and scalable solutions, whether it's web applications, machine learning models, or automation tools. With strong problem-solving skills and a keen interest in emerging technologies, I am always looking for opportunities to learn and innovate. Beyond coding, I have a deep passion for photography, capturing moments through my lens and exploring creativity in visual storytelling 
user_title:  Software Developeer | AI & Data Enthusiast
email: pvsprasanth0209@gmail.com
twitter_username: lorem_ipsum
github_username:  pvsp2003
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
